AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys resources required for Traffic Mirroring
Resources: 
  RecipientVM:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: False
      ImageId: ami-0fc970315c2d38f01
      InstanceType: t3a.micro
      IamInstanceProfile: !Ref MonitoringProfile
      Monitoring: true
      SubnetId: !ImportValue "PublicSubnet1"
      SecurityGroupIds:
        - !ImportValue "NoIngressSecurityGroup"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo -s
          amazon-linux-extras install -y epel
          yum install -y suricata
          mkdir /var/lib/suricata/rules
          echo 'alert tcp any any -> any any (msg:"TCP traffic detected"; sid:200001; rev:1;)' > /var/lib/suricata/rules/suricata.rules
          suricata -c /etc/suricata/suricata.yaml -k none -i eth0 -D
      Tags:
        - Key: Name
          Value: Recipient

  SenderVM:
    Type: AWS::EC2::Instance
    Properties:
      DisableApiTermination: False
      ImageId: ami-0fc970315c2d38f01
      InstanceType: t3a.micro
      IamInstanceProfile: !Ref MonitoringProfile
      Monitoring: true
      SubnetId: !ImportValue "PublicSubnet1"
      SecurityGroupIds:
        - !ImportValue "NoIngressSecurityGroup"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo yum install python3 -y
          sudo pip3 install pip --upgrade
      Tags:
        - Key: Name
          Value: Sender


  MonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service: "ec2.amazonaws.com"
              Action: "sts:AssumeRole"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"

  MonitoringProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: MonitoringProfile
      Path: /
      Roles: 
        - !Ref MonitoringRole